### ISSUE TITLE
Differences between faker cloud and faker.js

### ISSUE THREAD

**Issue by IanVS** [faker/faker-cloud#2]
I was [asked](https://github.com/Marak/faker.js/issues/1183#issuecomment-858707093) to open this issue here instead of at faker.  It's too bad that the issue was locked, since the link to this new issue won't show up.  :(

I'm just getting started learning and using faker, and I was looking through the examples at fakercloud.com/api to see examples of each of the types that are available. I found one that seemed perfect, but then noticed that it's not in the README on this repo. I've been looking through the code a bit to see if it's named differently, but can't find it, so I assume that maybe there are additional data types in faker cloud that are not in the core library, although this isn't clarified anywhere that I can find.

I see a similar question was asked in [#1179](https://github.com/Marak/faker.js/issues/1179), but was closed and locked without much (any) explanation. As a new user, I'm wondering what the plan is for faker.js and faker cloud. If they're different and have different capabilities, that's fine and of course your prerogative. But maybe there can be some kind of indication on fakercloud.com/api which ones are cloud-only, to avoid confusion?

**Comment by createthis** [comment]
I also want to know what is going on. It's unusual for a project repo to be completely turned off on github. The npm page is now pointing to a lot of links that give 404 codes.

**Comment by IanVS** [comment]
It looks like @Marak has chosen to take faker offline for good.  Time to look for other alternatives, it seems.  A good reminder that any project controlled by a single person can disappear, I guess.

**Comment by createthis** [comment]
The original project was MIT Licensed, so all we need is a new maintainer and a new repo to bring it back.

**Comment by ST-DDT** [comment]
There is already a fork that continues that work:

- https://fakerjs.dev/ (Project page)
- https://github.com/faker-js/faker (Github)

(I'm a maintainer in that project)
